#! /bin/sh

# only tiled layout
bspc desktop -l tiled

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  "#ffffff"
bspc config focused_border_color "#000000"
bspc config focus_follows_pointer false

bspc config window_gap 0
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio          0.5

# bspc rule -a '*' state=tiled
# bspc rule -a '*' fullscreen=on follow=on

# bspc rule -a TelegramDesktop desktop=9 follow=on
# bspc rule -a Telegram state=floating
# bspc rule -a '*' state=floating layer=above -o dialog=on

pgrep -x sxhkd > /dev/null || sxhkd &
~/dotfiles/scripts/polybar.sh &
pgrep -x redshift > /dev/null || redshift -l 50.4461248:30.5214979 -t 6500:3000 &
pgrep -x wired > /dev/null || wired &
~/dotfiles/scripts/to-light-theme.sh &
