[buildPlans.iosevka-arjaz]
family = "Iosevka Arjaz"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-arjaz.variants]
  inherits = "ss07"

    [buildPlans.iosevka-arjaz.variants.design]
    asterisk = "penta-low"
    paren = "flat-arc"
    brace = "straight"
    number-sign = "slanted"
    dollar = "open"
    cent = "open"
