export ZSH=~/.oh-my-zsh

export UPDATE_ZSH_DAYS=13

plugins=(
  git
  zsh-autosuggestions
  fast-syntax-highlighting
  # zsh-vim-mode
)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Aliases
alias em='emacsclient --alternate-editor="" -c . &; disown; exit'
alias vim=nvim
alias v=nvim
alias view='nvim -R'

alias p=python
alias ip='ipython -i --pprint'

alias btw=neofetch
alias :q=exit
alias code='cd ~/Code/'

alias l='exa -lah'
alias la='exa -lah'
alias ll='exa -lh'
alias ls=exa

export MANPAGER="sh -c 'col -bx | bat -l man -p'"

test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)

export PATH="$HOME/.dotfiles/scripts:$PATH"
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/share/racket/7.9/bin:$PATH"
export PATH="$HOME/Android/Sdk/platform-tools:$PATH"

# Theme
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
